name: Simple CI job

on:
  push:
    branches: [ "feature1" ]
  pull_request:
    branches: [ "feature1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: |
          echo "Hello, world!"
          echo "Hello, everyone!"