name: time.yml

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: time
        run: |
          current_date_time=$(date)
          echo "Current date and time: $current_date_time"
